// src/components/Header.tsx
import { Calendar } from "lucide-react";
import { Link } from "react-router-dom";

const Header = () => (
  <header className="border-b border-border bg-background px-6 py-4">
    <Link to="/" className="flex items-center gap-2">
      <Calendar className="h-6 w-6 text-primary" />
      <span className="text-xl font-bold text-foreground">SmartEvent</span>
    </Link>
  </header>
);

export default Header;

// src/components/Header.vue
<script setup>
import { Calendar } from 'lucide-vue-next'
</script>

<template>
  <header class="border-b border-border bg-background px-6 py-4">
    <RouterLink to="/" class="flex items-center gap-2">
      <Calendar class="h-6 w-6 text-primary" />
      <span class="text-xl font-bold text-foreground">SmartEvent</span>
    </RouterLink>
  </header>
</template>
